service: tm-test
frameworkVersion: '2'
configValidationMode: error

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: production
  profile: default
  region: ap-southeast-2
  memorySize: 128
  logRetentionInDays: 7
  stackTags:
    environment: "production"
    name: "tm-test"
  logs:
    restApi: true

functions:
  hello:
    handler: handler.hello
    name: tm-test
    description: tm test using Serverless framework
    events:
      - http:
          path: /
          method: get


plugins:
  - serverless-plugin-resource-tagging